universe = vanilla
executable = integrate_likelihood_extrinsic_batchmode
arguments = " --inj-xml overlap-grid-1.xml.gz --output-file ile-1-$(cluster)-$(process) --event $(macroevent) --time-marginalization --vectorized "
request_memory = 8192M
request_disk = 1024M
request_cpus = 2
request_gpus = 1
getenv = True
accounting_group = ligo.dev.o4.cbc.pe.lalinference
+SlurmPartition = "gpu"
log = logs/ile-1.$(cluster).$(process).log
error = logs/ile-1.$(cluster).$(process).err
output = logs/ile-1.$(cluster).$(process).out
notification = never
queue 8
