universe = vanilla
executable = util_ConstructIntrinsicPosterior_GenericCoordinates.py
arguments = " --input-net event-2.net --output-file marg-event-2.dat --idx $(macroidx) "
request_memory = 8192M
request_disk = 1024M
getenv = True
accounting_group = ligo.dev.o4.cbc.pe.lalinference
+SlurmPartition = "compute"
log = logs/marg-event-2.log
error = logs/marg-event-2.err
output = logs/marg-event-2.out
notification = never
queue 4
