universe = vanilla
executable = util_ConstructIntrinsicPosterior_GenericCoordinates.py
arguments = " --input-net event-1.net --output-file marg-event-1.dat --idx $(macroidx) "
request_memory = 8192M
request_disk = 1024M
getenv = True
accounting_group = ligo.dev.o4.cbc.pe.lalinference
+SlurmPartition = "compute"
log = logs/marg-event-1.log
error = logs/marg-event-1.err
output = logs/marg-event-1.out
notification = never
queue 4
